### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by wybyxiaohao** [xiaowuga/PrimFit#3]
Hi!

Thanks for the interesting work. We are following your work. When the code will be released? If you have no time, could you please also share the single primitive version with us, which you mentioned it in another issue? We sent you a private email, but haven't got reply yet.

Thank you!

**Comment by xiaowuga** [comment]
> Hi!
> 
> Thanks for the interesting work. We are following your work. When the code will be released? If you have no time, could you please also share the single primitive version with us, which you mentioned it in another issue? We sent you a private email, but haven't got reply yet.
> 
> Thank you!

This is a single primitive version of the GUI program that has been privately sent to you
